# Generated by Django 2.0.1 on 2018-02-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrados',
            new_name='Registrado',
        ),
    ]
